begin program.
import SPSSINC_CENSOR_TABLES
reload(SPSSINC_CENSOR_TABLES)
end program.

get file="c:/spss20/samples/english/employee data.sav".

DATASET ACTIVATE DataSet1.
* Custom Tables.
CTABLES
  /VLABELS VARIABLES=educ jobcat DISPLAY=LABEL
  /TABLE educ [COUNT F40.0] BY jobcat
  /CATEGORIES VARIABLES=educ jobcat ORDER=A KEY=VALUE EMPTY=INCLUDE MISSING=EXCLUDE.

SPSSINC CENSOR TABLES
CRITLABEL="Count" TESTTYPE="<" CRITVALUE=5
DIRECTION=ROW NEIGHBORS=0
SUBTYPE="customtable"
/OPTIONS APPENDCAPTION=YES.

CTABLES
  /VLABELS VARIABLES=educ jobcat DISPLAY=LABEL
  /TABLE educ [COUNT F40.0] BY jobcat
  /CATEGORIES VARIABLES=educ jobcat ORDER=A KEY=VALUE EMPTY=INCLUDE MISSING=EXCLUDE.

SPSSINC CENSOR TABLES
CRITLABEL="Count" TESTTYPE="<" CRITVALUE=5
DIRECTION=ROW NEIGHBORS=0
SUBTYPE="customtable"
/OPTIONS APPENDCAPTION=YES conditionalcaption=no

* no censoring but display caption.
CTABLES
  /VLABELS VARIABLES=educ jobcat DISPLAY=LABEL
  /TABLE educ [COUNT F40.0] BY jobcat
  /CATEGORIES VARIABLES=educ jobcat ORDER=A KEY=VALUE EMPTY=INCLUDE MISSING=EXCLUDE.

SPSSINC CENSOR TABLES
CRITLABEL="Count" TESTTYPE=">" CRITVALUE=500
DIRECTION=ROW NEIGHBORS=0
SUBTYPE="customtable"
/OPTIONS APPENDCAPTION=YES conditionalcaption=no

* no censoring but display caption conditionally..
CTABLES
  /VLABELS VARIABLES=educ jobcat DISPLAY=LABEL
  /TABLE educ [COUNT F40.0] BY jobcat
  /CATEGORIES VARIABLES=educ jobcat ORDER=A KEY=VALUE EMPTY=INCLUDE MISSING=EXCLUDE.

SPSSINC CENSOR TABLES
CRITLABEL="Count" TESTTYPE=">" CRITVALUE=500
DIRECTION=ROW NEIGHBORS=0
SUBTYPE="customtable"
/OPTIONS APPENDCAPTION=YES conditionalcaption=yes

* no censoring but display caption conditionally..
CTABLES
  /VLABELS VARIABLES=educ jobcat DISPLAY=LABEL
  /TABLE educ [COUNT F40.0] BY jobcat
  /CATEGORIES VARIABLES=educ jobcat ORDER=A KEY=VALUE EMPTY=INCLUDE MISSING=EXCLUDE.

SPSSINC CENSOR TABLES
CRITLABEL="Count" TESTTYPE=">" CRITVALUE=500
DIRECTION=ROW NEIGHBORS=0
SUBTYPE="customtable"
/OPTIONS APPENDCAPTION=YES conditionalcaption=yes.

* censoring but display caption conditionally..
CTABLES
  /VLABELS VARIABLES=educ jobcat DISPLAY=LABEL
  /TABLE educ [COUNT F40.0] BY jobcat
  /CATEGORIES VARIABLES=educ jobcat ORDER=A KEY=VALUE EMPTY=INCLUDE MISSING=EXCLUDE.

SPSSINC CENSOR TABLES
CRITLABEL="Count" TESTTYPE=">" CRITVALUE=100
DIRECTION=ROW NEIGHBORS=0
SUBTYPE="customtable"
/OPTIONS APPENDCAPTION=YES conditionalcaption=yes.

* censoring.  no caption.
CTABLES
  /VLABELS VARIABLES=educ jobcat DISPLAY=LABEL
  /TABLE educ [COUNT F40.0] BY jobcat
  /CATEGORIES VARIABLES=educ jobcat ORDER=A KEY=VALUE EMPTY=INCLUDE MISSING=EXCLUDE.

SPSSINC CENSOR TABLES
CRITLABEL="Count" TESTTYPE=">" CRITVALUE=100
DIRECTION=ROW NEIGHBORS=0
SUBTYPE="customtable"
/OPTIONS APPENDCAPTION=no conditionalcaption=yes.


